SYNEGRY-549 Create TLS certificate during upgrade
symless/synergy-core pull request #6835
Opened 2020-11-09 14:49 UTC by SerhiiGadzhilov

2020-11-09 15:09 UTC, andreacndn commented
Awesome, could you please leave a message with comments on this in the issues?
I guess we’ll still need to fix the UI big as suggested?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: sonarcloud[bot] <notifications@github.com>
Sent: Monday, November 9, 2020 3:02:23 PM
To: symless/synergy-core <synergy-core@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Subject: Re: [symless/synergy-core] SYNEGRY-549 Create TLS certificate during upgrade (#6835)


SonarCloud Quality Gate failed.

[Bug]<https://sonarcloud.io/project/issues?id=symless_synergy-core&pullRequest=6835&resolved=false&types=BUG> [A] <https://sonarcloud.io/project/issues?id=symless_synergy-core&pullRequest=6835&resolved=false&types=BUG>  0 Bugs<https://sonarcloud.io/project/issues?id=symless_synergy-core&pullRequest=6835&resolved=false&types=BUG>
[Vulnerability]<https://sonarcloud.io/project/issues?id=symless_synergy-core&pullRequest=6835&resolved=false&types=VULNERABILITY> [A] <https://sonarcloud.io/project/issues?id=symless_synergy-core&pullRequest=6835&resolved=false&types=VULNERABILITY>  0 Vulnerabilities<https://sonarcloud.io/project/issues?id=symless_synergy-core&pullRequest=6835&resolved=false&types=VULNERABILITY> (and [Security Hotspot] <https://sonarcloud.io/project/issues?id=symless_synergy-core&pullRequest=6835&resolved=false&types=SECURITY_HOTSPOT>  0 Security Hotspots<https://sonarcloud.io/project/issues?id=symless_synergy-core&pullRequest=6835&resolved=false&types=SECURITY_HOTSPOT> to review)
[Code Smell]<https://sonarcloud.io/project/issues?id=symless_synergy-core&pullRequest=6835&resolved=false&types=CODE_SMELL> [A] <https://sonarcloud.io/project/issues?id=symless_synergy-core&pullRequest=6835&resolved=false&types=CODE_SMELL>  0 Code Smells<https://sonarcloud.io/project/issues?id=symless_synergy-core&pullRequest=6835&resolved=false&types=CODE_SMELL>

[0.0%]<https://sonarcloud.io/component_measures?id=symless_synergy-core&pullRequest=6835&metric=new_coverage&view=list> 0.0% Coverage<https://sonarcloud.io/component_measures?id=symless_synergy-core&pullRequest=6835&metric=new_coverage&view=list>
[0.0%]<https://sonarcloud.io/component_measures?id=symless_synergy-core&pullRequest=6835&metric=new_duplicated_lines_density&view=list> 0.0% Duplication<https://sonarcloud.io/component_measures?id=symless_synergy-core&pullRequest=6835&metric=new_duplicated_lines_density&view=list>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://github.com/symless/synergy-core/pull/6835#issuecomment-724068198>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AQP57ANQ7KE7K7HS4MCPPHLSO7777ANCNFSM4TPOBB5Q>.

2020-11-09 15:48 UTC, SerhiiGadzhilov commented
The coverage is 0 because all changes were done in gui code which doesn't have infrastructure for testing now.

2020-11-10 05:59 UTC, ignacionr requested changes
The code works. I am a bit worried about its organisation. We know GUI isn't Synergy 1's strongest suit, so all domain logic needs to be ready to depart on short notice. If there's a good reason to let the dialog take care of SSL generation, please share.
But again, the code does the generation, it does the override when needed, so the most important part, is great work.

2020-11-10 05:59 UTC, ignacionr commented on src/gui/src/AppConfig.cpp
> +        generateCertificate();
I don't pretend that you should come up with an architectural change at this point. But I think you must be as unhappy as I am to see the code that works out business rules, so tightly mixed with the GUI and ultimately dependent on Qt. At this point, let us just make sure we have an item in the backlog to "make business rules independent from a Qt modeled GUI."

2020-11-10 05:59 UTC, ignacionr commented on src/gui/src/SettingsDialog.cpp
> -    if(m_pCheckBoxEnableCrypto->isChecked()) {
Shouldn't we just spawn a configuration change (App Config) and that in turn run this kind of checks? I am concerned that we may end up re-creating the certificate twice in any case. Also applies the same concern as before (GUI code running the domain rules logic from within).

2020-11-10 05:59 UTC, ignacionr commented on src/gui/src/SettingsDialog.cpp
> -void SettingsDialog::regenerateSSLCert() {
I would be kind of less unhappy to have the SSL generation code at the AppConfig object, even if it's not ideal (still tied to Qt and ultimately to GUI) it seems more abstracted than directly on the dialog. But there could be a reason why you moved it here, kindly share?

2020-11-10 09:28 UTC, SerhiiGadzhilov commented on src/gui/src/AppConfig.cpp
> +        generateCertificate();
Yes, I'm not happy as you but I'm not sure that we need such wide task as "make business rules independent from a Qt modeled GUI."
Tasks like this make code and architecture better but they don't provide value for the end users.

I think about such tasks as about revolution which can break something and can provide a lot af benefits in long term.
I like evolution way where we move to good design through small steps and design is constructed according to current users needs.

I think it's a topiс for discussion and the truth is somewhere in between.

2020-11-10 09:28 UTC, SerhiiGadzhilov commented on src/gui/src/SettingsDialog.cpp
> -    if(m_pCheckBoxEnableCrypto->isChecked()) {
Actually this is what I did.
I removed checks from SettingsDialog and added them into AppConfig::setCryptoEnabled.
In SettingsDialog we just call AppConfig::setCryptoEnabled and this method does checks and generate certificate if it's needed.

2020-11-10 09:29 UTC, SerhiiGadzhilov commented on src/gui/src/SettingsDialog.cpp
> -void SettingsDialog::regenerateSSLCert() {
Actually this is exactly what I did.
I removed TLS certificate code generation from SettingsDialog and added a new method "AppConfig::generateCertificate".
Now SettingsDialog just calls appropriate AppConfig methods as result of different GUI events.

2020-11-10 10:48 UTC, ignacionr commented on src/gui/src/SettingsDialog.cpp
> -    if(m_pCheckBoxEnableCrypto->isChecked()) {
I will take a note to myself: make sure you read chages on the correct side! :D :1st_place_medal: Thank you.

2020-11-10 10:49 UTC, ignacionr commented on src/gui/src/SettingsDialog.cpp
> -void SettingsDialog::regenerateSSLCert() {
:1st_place_medal: thank you; this is the best possible approach right now

2020-11-10 10:53 UTC, ignacionr commented on src/gui/src/AppConfig.cpp
> +        generateCertificate();
Agreed that it's an interesting topic for a discussion that doesn't belong in this PR. Only let's have this conversation at some point. I'm sure you too feel the need for the unit tests that are amiss here, and they would be much easier to come up with, should there be more separation between the UI and everything else. Again, more using this PR as food for thoughts than anything else.

By the way, now that I see it in the right way (that is what you actually did) I see that you're using the excuse of solving things like this, to add quality in general. :+1:

2020-11-10 10:54 UTC, ignacionr approved these changes

2020-11-10 11:26 UTC, merged