Adding MacOS CI Build Steps for Homebrew Cleanup
symless/synergy-core pull request #6863
Opened 2020-12-07 13:15 UTC by ignacionr

Homebrew was acting up.

2020-12-09 09:44 UTC, andreacndn requested changes
@ignacionr could you please update the change log?

2020-12-10 09:41 UTC, ignacionr commented
> @ignacionr could you please update the change log?

Sure, as soon as we isolate the one approach that finally works :)

2020-12-11 09:45 UTC, andreacndn requested changes
Looks like the branch now has conflicts

2020-12-15 11:59 UTC, andreacndn submitted a review, later dismissed

2020-12-15 12:51 UTC, SerhiiGadzhilov approved these changes

2020-12-15 12:53 UTC, merged