refactored and setup retries
symless/synergy-core pull request #6889
Opened 2020-12-28 05:41 UTC by ignacionr

2020-12-31 14:26 UTC, SerhiiGadzhilov commented on src/gui/src/MainWindow.cpp
> +    QAction *trayMenu[] = {
Do we really need C-style array?
Isn't it better to use std::vector?

2020-12-31 14:26 UTC, SerhiiGadzhilov commented on src/gui/src/TrayIcon.h
> +        m_pTrayIconMenu = std::make_unique<QMenu>();
As I can see before these changes QMenu had parent MainWindow: m_pTrayIconMenu = new QMenu(this);
Is it ok that QMenu is created without parent?

2020-12-31 14:26 UTC, SerhiiGadzhilov commented on src/gui/src/TrayIcon.h
> +    void create(TActionIterator *begin, TActionIterator *end, TConnector connector)
Maybe it's better to use const std::vector& instead of TActionIterator *begin, TActionIterator *end

2020-12-31 14:26 UTC, SerhiiGadzhilov commented on src/gui/src/TrayIcon.cpp
> +#include <iostream>
Looks like <iostream> is not needed here?

2021-01-05 02:29 UTC, ignacionr commented on src/gui/src/TrayIcon.h
> +    void create(TActionIterator *begin, TActionIterator *end, TConnector connector)
Sorry I don't agree. The point of using abstract iterators is to allow for any shape of container (including base arrays, std::vector, std::list, etc).

2021-01-05 02:30 UTC, ignacionr commented on src/gui/src/TrayIcon.h
> +        m_pTrayIconMenu = std::make_unique<QMenu>();
Yes it is okay. The difference is lifespan. When you use the parent parameter, the menu will be destroyed by Qt when the parent fades away. My design rather uses unique_ptr to take care of that in an easier fashion, and will eventually let the code be increasingly less dependent on Qt.

2021-01-05 02:32 UTC, ignacionr commented on src/gui/src/MainWindow.cpp
> +    QAction *trayMenu[] = {
An alternative could be std::array (std::vector would be needed for dynamically allocations, which is not needed).
But since this code is better read and understood directly, I prefer the most basic representation.

2021-01-05 02:32 UTC, ignacionr commented on src/gui/src/TrayIcon.cpp
> +#include <iostream>
Correct! I will remove.

2021-01-05 03:05 UTC, ignacionr commented on src/gui/src/MainWindow.cpp
> +    QAction *trayMenu[] = {
I will take your suggestion of using an STL container, but opt for std::array because there is no need for dynamic allocations.

2021-01-05 03:14 UTC, ignacionr commented on src/gui/src/TrayIcon.h
> +    void create(TActionIterator *begin, TActionIterator *end, TConnector connector)
Since I'm taking the first suggestion to avoid basic arrays, then basic arrays are out of the picture, then a container could be a better argument. This should also suit your request.

2021-01-08 10:42 UTC, SerhiiGadzhilov requested changes
Could you please merge ChangeLog from master and update it.
This task should be inside section "v1.13.1-snapshot"

2021-01-09 09:33 UTC, ignacionr commented
> Could you please merge ChangeLog from master and update it.
> This task should be inside section "v1.13.1-snapshot"

This was done. Please review.

2021-01-10 13:30 UTC, SerhiiGadzhilov approved these changes

2021-01-10 13:31 UTC, merged

2021-01-10 13:49 UTC, SerhiiGadzhilov commented
Centos7.6 build failed with the following error: 
```
/__w/1/s/src/gui/src/TrayIcon.h:19:27: error: 'make_unique' is not a member of 'std'
         m_pTrayIconMenu = std::make_unique<QMenu>();
```
Could you please, check the issue.

2021-01-10 17:28 UTC, ignacionr commented
> @ignacionr Centos7.6 build failed with the following error:
> 
> ```
> /__w/1/s/src/gui/src/TrayIcon.h:19:27: error: 'make_unique' is not a member of 'std'
>          m_pTrayIconMenu = std::make_unique<QMenu>();
> ```
> 
> Could you please, check the issue.

@SerhiiGadzhilov the issue seems to be that the installed compiler isn't even supporting C++14. Is it possible that the image has a very outdated compiler installed?

2021-01-10 17:29 UTC, andreacndn commented
> > @ignacionr Centos7.6 build failed with the following error:
> > ```
> > /__w/1/s/src/gui/src/TrayIcon.h:19:27: error: 'make_unique' is not a member of 'std'
> >          m_pTrayIconMenu = std::make_unique<QMenu>();
> > ```
> > 
> > 
> > Could you please, check the issue.
> 
> @SerhiiGadzhilov the issue seems to be that the installed compiler isn't even supporting C++14. Is it possible that the image has a very outdated compiler installed?

Ignacio, could you please tomorrow update the compiler on this image?

2021-01-10 17:39 UTC, ignacionr commented
@andreacndn replied over Slack