Modifying the Azure Pipeline so that CentOS 7.6 gets additional required commands
symless/synergy-core pull request #6906
Opened 2021-01-12 05:59 UTC by ignacionr

For building on CentOS 7.6, we need to enable the development tools newer version, each time we issue a command.

2021-01-15 07:39 UTC, SerhiiGadzhilov requested changes

2021-01-15 07:39 UTC, SerhiiGadzhilov commented on CI/Linux/linux-build.yml
> +      GIT_COMMIT: $(Build.SourceVersion)
As I can see the “devtoolset” was added only for the “Standard” version build. 
Maybe the “Enterprise” build should be updated as well?
Isn't it better to include the "devtoolset" into docker image for CentOS 7.6?

2021-01-15 11:36 UTC, andreacndn commented on CI/Linux/linux-build.yml
> +      GIT_COMMIT: $(Build.SourceVersion)
Agreed that the requirement was to update the CentOS docker image

2021-01-15 11:37 UTC, andreacndn requested changes
Agreed that the requirement was to update the CentOS docker image

2021-02-08 06:52 UTC, SerhiiGadzhilov commented
Fixed under #6937

2021-02-08 06:52 UTC, closed without merging