duplicating text spaces after dot
symless/synergy-core pull request #6914
Opened 2021-01-18 14:11 UTC by ignacionr

2021-01-20 15:24 UTC, SerhiiGadzhilov requested changes

2021-01-20 15:24 UTC, SerhiiGadzhilov commented on src/gui/src/main.cpp
>          setupWizard.show();
setupWizard is destructed before app.exec() as result we will never see Setup Wizard window.

2021-01-21 09:14 UTC, ignacionr commented on src/gui/src/main.cpp
>          setupWizard.show();
@SerhiiGadzhilov I truly don't understand what you mean. The setupWizard will only be shown within the if condition where it is now also created. There is no other condition that will show it, and it is thus not needed. Please recheck.

2021-01-21 09:32 UTC, ignacionr commented on src/gui/src/main.cpp
>          setupWizard.show();
Great catch! The new approach is equivalent to the original, but improves avoiding construction if unneeded.

2021-01-21 10:45 UTC, SerhiiGadzhilov approved these changes

2021-01-21 10:46 UTC, merged