SYNERGY 512 SonarCloud vulnerabilities in Synergy-Core
symless/synergy-core pull request #6971
Opened 2021-03-30 22:25 UTC by abatyiev

2021-04-02 14:37 UTC, SerhiiGadzhilov requested changes

2021-04-02 14:37 UTC, SerhiiGadzhilov commented on src/lib/platform/XWindowsClipboard.cpp
> +                data = tmp;
This code looks ok but looks like it can be easily moved to separate function with one parameter to reduce the complexity.

2021-04-02 14:37 UTC, SerhiiGadzhilov commented on src/lib/platform/XWindowsClipboard.cpp
> +                XFree(type);
This code looks ok but it's better to use smart pointers like std::unique_ptr in such cases to comply with RAII.

2021-04-05 00:08 UTC, abatyiev commented on src/gui/src/QUtility.cpp
>          }
You are right, but I'm not sure about all functional of synergy application, so the main idea of all my first changes - do not change logic, just fixes. In future, with all settled up tests(including different OS and connections) and with experience of usage, I'll be more brave in deleting or changing logic. For now, after your comment I'm free to delete this code block, thanks.

2021-04-05 00:08 UTC, abatyiev commented on src/lib/net/TCPListenSocket.cpp
> +        LOG((CLOG_INFO "error while closing TCP socket"));
Fixed

2021-04-05 00:11 UTC, abatyiev commented on src/lib/platform/XWindowsClipboard.cpp
> +                data = tmp;
Beside of complexity this code also has logical errors(converting to hex going wrong). 1128 line contains byte offset of uchar but with value 16 instead of 4. I think, that even log changes can lead to problems, when you are not well familiar with projects, that's why I prefer to do my first changes with minimum of intervention. But if you insist - I'll move this part to new function and, also, can fix char conversion.

2021-04-05 00:25 UTC, abatyiev commented on src/lib/platform/XWindowsClipboard.cpp
> +                XFree(type);
Same with previous comments, based on your experience and advice this code can be rewritten

2021-04-06 09:48 UTC, SerhiiGadzhilov commented on src/lib/platform/XWindowsClipboard.cpp
> +                data = tmp;
@abatyiev Could you please, create a new task in Jira for the problem with hex conversion. 
We will change this code under the new task because it requires thorough investigation.
I will merge this code as is.

2021-04-06 10:01 UTC, SerhiiGadzhilov approved these changes

2021-04-06 10:02 UTC, merged