Synergy 885 mac client listens on ipv4 only but attempts to connect on ipv6
symless/synergy-core pull request #6983
Opened 2021-04-21 16:02 UTC by abatyiev

2021-04-22 10:35 UTC, SerhiiGadzhilov requested changes

2021-04-22 10:35 UTC, SerhiiGadzhilov commented on src/lib/net/NetworkAddress.cpp
> +        m_hostname = m_hostname.substr(0, hostIt - 1);
1. If the hostname contains only port (“:24800”) the system doesn’t erase it from the hostname as the result we have the following error “synergys: unknown error for: :24800:24800”.  

2. As I can see this function doesn't have external dependencies hence it could be easily covered with unit tests to fix "SonarCloud Quality Gate failed."

2021-04-25 21:23 UTC, abatyiev commented on src/lib/net/NetworkAddress.cpp
> +        m_hostname = m_hostname.substr(0, hostIt - 1);
Thanks! All issues fixed!

2021-04-26 07:37 UTC, SerhiiGadzhilov approved these changes

2021-04-26 07:37 UTC, merged