SYNERGY-907 Client tray language switcher reverts to EN
symless/synergy-core pull request #6989
Opened 2021-04-28 22:27 UTC by abatyiev

*Dummy commit to update test coverage statistic

2021-05-07 12:32 UTC, SerhiiGadzhilov requested changes

2021-05-07 12:32 UTC, SerhiiGadzhilov commented on src/gui/src/AppConfig.cpp
> +    m_LanguageSync              = loadSetting(kLanguageSync, true).toBool();
According to the task description the new option should be disabled by default.
According to the code this option is enabled by default.

2021-05-07 12:32 UTC, SerhiiGadzhilov commented on src/gui/src/AppConfig.cpp
> +        setSetting(kLanguageSync, m_LanguageSync);
Could you please, add the new option into the array AppConfig::m_SynergySettingsName.
You added “kLanguageSync” into the “enum Setting”. 
This constant is used to get value from the AppConfig::m_SynergySettingsName.
AppConfig::m_SynergySettingsName was not updated as a result the program reads outside of the array and the setting doesn’t work.

2021-05-07 12:32 UTC, SerhiiGadzhilov commented on src/gui/src/MainWindow.cpp
> +    }
As I understand this option is only for synergy client.
I think it should be hidden for servers.
It could lead to misunderstanding and complains from users if users set this option on the server machine and it will not work.

2021-05-11 17:35 UTC, abatyiev commented on src/gui/src/AppConfig.cpp
> +    m_LanguageSync              = loadSetting(kLanguageSync, true).toBool();
Fixed! Thanks!

2021-05-11 17:35 UTC, abatyiev commented on src/gui/src/AppConfig.cpp
> +        setSetting(kLanguageSync, m_LanguageSync);
Fixed! Thanks!

2021-05-11 17:38 UTC, abatyiev commented on src/gui/src/MainWindow.cpp
> +    }
This code is already in function `MainWindow::clientArgs`. So will be added only for client start. Also parsing of this flag is in `ArgParser::parseClientArgs`. So we are ready for this flag only when parsing clients args.

2021-05-11 18:33 UTC, SerhiiGadzhilov commented on src/gui/src/MainWindow.cpp
> +    }
Yes, that's why I think we should hide this flag on GUI for servers. 
This flag doesn't work for servers and should be hidden for users.
For example user can set this flag on server side and expect that all clients will work according to this flag but it's not true.

2021-05-12 10:49 UTC, andreacndn commented on src/gui/src/MainWindow.cpp
> +    }
Agreed

2021-05-13 01:24 UTC, abatyiev commented on src/gui/src/MainWindow.cpp
> +    }
Done! Now This setting is hidden when server mode is active.

2021-05-13 06:29 UTC, SerhiiGadzhilov approved these changes

2021-05-13 06:30 UTC, merged