SYNERGY-960 Test IPv6 support on various Operating systems
symless/synergy-core pull request #7002
Opened 2021-05-18 07:11 UTC by abatyiev

*Add client listner on both ipv4 and ipv6
*Add ipv6 support on windows
*Fix squad interface formatting
*Fix ipv6 any addr scocket bind

2021-05-19 09:39 UTC, SerhiiGadzhilov requested changes

2021-05-19 09:39 UTC, SerhiiGadzhilov commented on src/lib/net/NetworkAddress.cpp
> +    *this = addr;
I think it's not safe to copy NetworkAddress this way.
I think function ARCH->copyAddr(addr.m_address) should be used to copy m_address which allocates a new memory instead of copy a pointer.

2021-05-19 09:41 UTC, andreacndn commented on src/gui/src/MainWindow.cpp
> -                QString format = "<span style=\"color:#4285F4;\">%1</span>";
@SerhiiGadzhilov Agreed, these changes should be discarded, and revert to the previous behaviour and UI

2022-04-27 11:04 UTC, SerhiiGadzhilov commented
This PR should be totally rewritten if we need this functionality

2022-04-27 11:04 UTC, closed without merging