SYNERGY-988 Mac client does not scroll in natural direction
symless/synergy-core pull request #7012
Opened 2021-05-21 09:51 UTC by igor-sikachyna

2021-05-26 12:04 UTC, SerhiiGadzhilov requested changes

2021-05-26 13:42 UTC, igor-sikachyna commented on src/lib/platform/OSXScreen.mm
> +		m_scrollDirection = [[[NSUserDefaults standardUserDefaults] objectForKey:@"com.apple.swipescrolldirection"] boolValue] ? 1 : -1;
The fix itself is to make sure that scroll value is positive for natural scrolling direction on client. So `m_scrollDirection = 1` corresponds to the positive direction. But that is a question of convention

2021-05-26 13:43 UTC, igor-sikachyna commented on src/lib/platform/OSXScreen.mm
> +
I am looking into it, probably you are right, just need to check if it won't cause problems for `y` scrolling

2021-05-26 13:57 UTC, SerhiiGadzhilov commented on src/lib/platform/OSXScreen.mm
> +		m_scrollDirection = [[[NSUserDefaults standardUserDefaults] objectForKey:@"com.apple.swipescrolldirection"] boolValue] ? 1 : -1;
Could you please, recheck that a mouse which is controlled by synergy works in the same way as a hardware mouse which is connected directly to the computer.

2021-05-26 14:45 UTC, igor-sikachyna commented
@SerhiiGadzhilov, I've checked and your comments were indeed correct, updated the code accordingly

2021-05-27 05:45 UTC, SerhiiGadzhilov approved these changes

2021-05-27 05:45 UTC, merged