Synergy 907 client tray language switcher reverts to en
symless/synergy-core pull request #7038
Opened 2021-06-10 15:23 UTC by abatyiev

2021-06-30 12:28 UTC, SerhiiGadzhilov requested changes
Could you please, resolve conflicts and sonar issues.

2021-07-01 07:30 UTC, abatyiev commented
For now Sonar warnings are, mainly, about files tinyxml2.cpp and tinyxml2.h. This file is from open source, well-known and tested library [tinyxml2](https://github.com/leethomason/tinyxml2), I think it is better to do not modify these files and add them to Sonar exclude list.

2021-07-01 15:41 UTC, SerhiiGadzhilov requested changes
Could you please, add checkbox into the "Settings" window.

2021-07-05 07:32 UTC, abatyiev commented on src/lib/client/Client.cpp
> +                                           String("This languages are required for client proper work: ") + missedLanguages);
Thanks! Fixed

2021-07-05 07:32 UTC, abatyiev commented on src/lib/server/ClientProxyUnknown.h
> +#include "base/String.h"
Fixed

2021-07-05 07:32 UTC, abatyiev commented on src/lib/server/Server.cpp
> +    // must have a primary client and it must have a canonical name
Fixed

2021-08-13 14:22 UTC, SerhiiGadzhilov requested changes
Could you please, resolve conflict

2021-08-13 14:22 UTC, SerhiiGadzhilov commented on ChangeLog
> +- #7038 Fix client and server different keyboard layout errors
Could you please, resolve conflict and  move this task under section v1.14.2

2021-08-13 14:22 UTC, SerhiiGadzhilov commented on src/lib/synergy/unix/X11LayoutsParser.cpp
> +    std::ifstream file("/etc/default/keyboard");
Is it possible to use the X11 API instead of parsing “/etc/default/keyboard”?

2021-08-17 09:28 UTC, abatyiev commented on src/lib/synergy/unix/X11LayoutsParser.cpp
> +    std::ifstream file("/etc/default/keyboard");
Unfortunately, there is no useful X11 api to get all installed languages, parsing of the "/etc/default/keyboard" file is the onliest way to get full language list

2021-08-19 08:07 UTC, abatyiev commented on ChangeLog
> +- #7038 Fix client and server different keyboard layout errors
Fixed

2021-08-20 07:18 UTC, abatyiev commented on src/lib/client/Client.cpp
> +    }
This blocks of code for different Synergy parts. One of them is for client, other - for server. For now, mainly, they are same, but it is incorrect to combine them because they works in different time and and for different logic

2021-08-25 08:58 UTC, SerhiiGadzhilov requested changes
Looks like tinyxml has too many issues.
Could you please, try to use https://github.com/zeux/pugixml instead of tinyxml.
Also include it as an external module as it’s done for WinToast and googletest.
In this case this module will be updated with all latest fixes from the official repo.

2021-08-30 09:06 UTC, abatyiev commented
TinyXML replaced with pugixml, added as a git submodule. Thanks

2021-08-30 18:26 UTC, SerhiiGadzhilov requested changes
Looks like synchronization doesn’t work.
The following scenario doesn’t work as for me:

Initial conditions:
Server - Windows
Server Language: RU, EN
Client - MacOS
Client Languages: RU, EN, UK
The option to sync languages is set on the client.

Step 1
Select language EN on the server
Select language RU on the client
Connect server and client
Move cursor to the client and type text
Expected:
Language on the client is switched to server (EN)
The text is typed in English
Actual:
Language on the client was not switched to server (EN)
The text is typed in Russian

Is it possible to increase test coverage for the new code?

2021-08-30 18:26 UTC, SerhiiGadzhilov commented on src/lib/server/ClientProxyUnknown.cpp
> +        }
The synergy server always shows notification about language synchronization despite the option language sync.

As I understand from the last comment in the task we should show notifications only on the client side.
These notifications should be shown in two cases:
- when the client connects to the server
- ​​every time the focus is on synergy client and the user is typing (server is sending keystrokes to the client)

As I understand, only the first point was implemented.
@andreacndn Could you please, confirm that my understanding is correct.

2021-09-01 03:26 UTC, abatyiev commented on src/gui/src/MainWindow.cpp
> +
Unfortunately, because of synergy network protocol limitation, only notifications, at start of session, are implemented. Test coverage is in progress, soon will be ready!

2021-09-01 03:26 UTC, abatyiev commented on src/gui/src/MainWindow.cpp
> +
"--sync-language" moved to clients config, thanks!

2021-09-01 03:26 UTC, abatyiev commented on src/lib/synergy/ArgParser.cpp
> +        else if (isArg(i, argc, argv, nullptr, "--sync-language", 1)) {
Fixed! Thanks!

2021-09-07 14:11 UTC, SerhiiGadzhilov requested changes
As I can see the following scenario is still doesn’t work:

Initial conditions:
Server - Windows
Server Language: RU, EN
Client - MacOS
Client Languages: RU, EN, UK
The option to sync languages is set on the client.

Step 1
Select language EN on the server
Select language RU on the client
Connect server and client
Move cursor to the client and type text

Expected:
Language on the client is switched to server (EN)
The text is typed in English

Actual (Problem):
Language on the client was not switched to server (EN)
The text is typed in Russian

2021-09-14 08:09 UTC, SerhiiGadzhilov requested changes
As I can see the scenario described above is still doesn't work.
The first issue is that  `kMsgDKeyDown`  has incorrect format: `"DKDN%2i%2i%2i%s"`
As result language is not send to the client.

After I fixed the format and the client receives the language the scenario still doesn't work.

2021-09-30 11:34 UTC, SerhiiGadzhilov requested changes
Language switching doesn’t work if Windows is a server.

Scenario:
Server - Windows; Language EN
Client - Linux/Mac; Language EN
Language sync is on.

Step 1
Connect server and client
Change server language to RU
Go client and type text
Expected: The text is typed in RU
Actual: The text is typed in EN

Note: During switching from server to client the server switches to client language (EN). 
When moving back to server language is switched back (RU).

2021-10-04 09:49 UTC, SerhiiGadzhilov requested changes

2021-10-04 09:49 UTC, SerhiiGadzhilov commented on src/lib/platform/OSXKeyState.cpp
> +    if(!canBeSetted || canBeSetted == FALSE) {
Isn't it's the same as if(!canBeSetted)

2021-10-04 09:49 UTC, SerhiiGadzhilov commented on src/lib/platform/OSXKeyState.cpp
> +                ARCH->sleep(.01);
Isn’t it better to move `ARCH->sleep(.01);` inside `setGroup`?

2021-10-04 09:49 UTC, SerhiiGadzhilov commented on src/lib/platform/MSWindowsDesks.cpp
> -                AttachThreadInput(thatThread, thisThread, FALSE);
I'm really worry about this change because we can break something.
According to Microsoft documentation SetForegroundWindow shouldn't work for background processes.
(https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setforegroundwindow)

In any case this change is incorrect because if we remove `AttachThreadInput` we don't need anymore `GetWindowThreadProcessId` inside this condition. Also if we remove `ActivateKeyboardLayout` we don't need `keyLayout` parameter. In this case we should remove this parameter and fix code which calls this function.

From my perspective we should restore this code and find another solution or discuss possible impact if we don't fix the problem and maybe leave it as is for now.

2021-10-04 09:49 UTC, SerhiiGadzhilov commented on src/lib/platform/MSWindowsDesks.cpp
> +    }
As I can see we have the same code in `MSWindowsDesks::MSWindowsDesks, MSWindowsScreen::leave` and `AppUtilWindows::getCurrentLanguageCode.` Maybe we can move it into separate function and use this function in all these places?

2021-10-04 13:54 UTC, SerhiiGadzhilov commented on src/lib/platform/OSXKeyState.cpp
> +    if(!canBeSetted || canBeSetted == FALSE) {
Fixed

2021-10-04 13:54 UTC, SerhiiGadzhilov commented on src/lib/platform/OSXKeyState.cpp
> +                ARCH->sleep(.01);
Fixed

2021-10-04 15:07 UTC, SerhiiGadzhilov commented on src/lib/platform/MSWindowsDesks.cpp
> -                AttachThreadInput(thatThread, thisThread, FALSE);
Fixed

2021-10-04 15:07 UTC, SerhiiGadzhilov commented on src/lib/platform/MSWindowsDesks.cpp
> +    }
Fixed

2021-10-04 15:50 UTC, SerhiiGadzhilov approved these changes

2021-10-04 15:51 UTC, merged