SYNERGY-1032 - Add MacOS version check and disabl UserNotification library if needed
symless/synergy-core pull request #7046
Opened 2021-07-01 08:01 UTC by igor-sikachyna

2021-07-01 13:50 UTC, SerhiiGadzhilov requested changes

2021-07-01 13:50 UTC, SerhiiGadzhilov commented on azure-pipelines.yml
> +          version: 10.15
This variable is used in CI/mac_build.yml in the following way:
-DCMAKE_OSX_DEPLOYMENT_TARGET=$(version)
According to synergy web-site we support the following versions:
- macOS BigSur (11) Intel and Apple M1
- macOS Catalina (10.15)
- macOS Mojave (10.14)
- macOS High Sierra 10.13

We have separate builds for macOS 10.13 and for M1.
We have only one build for 10.14, 10.15, 11(Intel).
If CMAKE_OSX_DEPLOYMENT_TARGET is set to 10.15 this build will not work on 10.14.

I think “version: 10.15” should be changed to “version: 10.14” to support macOS10.14.

2021-07-02 09:08 UTC, igor-sikachyna commented on azure-pipelines.yml
> +          version: 10.15
Agree, updated to by `10.14` instead, does not impact other changes since UserNotification library was added in `10.14`

2021-07-02 09:40 UTC, SerhiiGadzhilov approved these changes

2021-07-02 09:40 UTC, merged