SYNERGY-856 - Force prevent sleep
symless/synergy-core pull request #7047
Opened 2021-07-01 12:12 UTC by igor-sikachyna

2021-07-05 13:27 UTC, SerhiiGadzhilov requested changes

2021-07-05 13:27 UTC, SerhiiGadzhilov commented on src/gui/src/MainWindow.cpp
> +#endif
As I can see for mac and windows this functionality is implemented through the command line option “--prevent-sleep” but for Linux it’s implemented inside MainWindow.
As a result we have inconsistency which doesn’t allow us to use this functionality through the command line. 
For example it’s a real problem for Synergy 3 which has another GUI and passes options through the command line. Such logic shouldn’t be implemented inside GUI code.

2021-07-05 13:27 UTC, SerhiiGadzhilov commented on src/gui/src/MainWindow.cpp
> +                reply = screenSaverInterface.call("Inhibit", "nzuri-video Downloader", "REASON");
What is "nzuri-video Downloader"?

2021-07-08 08:05 UTC, SerhiiGadzhilov requested changes

2021-07-08 08:05 UTC, SerhiiGadzhilov commented on src/lib/platform/XWindowsScreen.cpp
> +		LOG((CLOG_INFO "Failed to prevent system from going to sleep"));
Prevent sleep doesn't work on my Ubuntu 20.04.
I always receive the following message: "Failed to prevent system from going to sleep".
Does it work on your Linux system?
Is it possible to add a reason of the failure to the traces?

2021-07-08 11:20 UTC, igor-sikachyna commented on src/gui/src/MainWindow.cpp
> +
Agree, removed

2021-07-08 11:21 UTC, igor-sikachyna commented on src/lib/platform/XWindowsScreen.cpp
> +		LOG((CLOG_INFO "Failed to prevent system from going to sleep"));
Added more verbose output to the errors occurring during sleep prevention. Also tested on my Ubuntu 20.04 VM and it seems to be working fine.

2021-07-09 10:46 UTC, SerhiiGadzhilov requested changes

2021-07-09 10:46 UTC, SerhiiGadzhilov commented on src/lib/platform/XWindowsScreen.cpp
> +
Could you please, remove these unused prototypes.

2021-07-12 09:44 UTC, SerhiiGadzhilov approved these changes

2021-07-12 09:44 UTC, merged