Add M1 workflow
symless/synergy-core pull request #7098
Opened 2021-09-29 09:44 UTC by aquacash5

Add workflows for apple's M1 platform

2021-09-30 07:28 UTC, SerhiiGadzhilov requested changes

2021-09-30 07:28 UTC, SerhiiGadzhilov commented on .github/workflows/aws-upload-windows.yml
> +      - name: Set up QT variables
As I can this task doesn't setup QT variables anymore.
Maybe it's better to move this code into `"Install OpenSSL"`
Also as I can see we have only "x64" build hence we can remove the following condition: `if ('${{ matrix.arch }}' -eq 'x64')`

2021-09-30 07:28 UTC, SerhiiGadzhilov commented on .github/workflows/aws-upload-mac.yml
> +            destination: macOS_arm64
As I can see .github/workflows/aws-upload-mac-10.13.yml was removed and .github/workflows/aws-upload-mac.yml doesn't have macOS10.13.
We don't need it anymore?

2021-09-30 07:28 UTC, SerhiiGadzhilov commented on src/cmd/CMakeLists.txt
> -endif (SYNERGY_BUILD_LEGACY_SERVICE)
As I can see we still have the option `SYNERGY_BUILD_LEGACY_SERVICE` inside `CMakeLists.txt` but after this change it does nothing. Looks like we need to remove the option or revert changes in `src/cmd/CMakeLists.txt`.

2021-09-30 08:11 UTC, aquacash5 commented on .github/workflows/aws-upload-mac.yml
> +            destination: macOS_arm64
For the core builds, I don't think we need macOS 10.13 builds.

2021-09-30 08:13 UTC, aquacash5 commented on src/cmd/CMakeLists.txt
> -endif (SYNERGY_BUILD_LEGACY_SERVICE)
You are correct. I will make that change

2021-09-30 08:33 UTC, aquacash5 commented on .github/workflows/aws-upload-windows.yml
> +      - name: Set up QT variables
Until we need a 32-bit version, I will set the action to only make a 64-bit version.

2021-10-01 07:55 UTC, SerhiiGadzhilov approved these changes

2021-10-01 07:55 UTC, merged

2021-10-01 08:04 UTC, SerhiiGadzhilov commented
@aquacash5 Could you please, check what is wrong with actions after merging this PR
![5A9AD548-CADD-4D8A-9642-1A4CA4A8411E](https://user-images.githubusercontent.com/71632867/135586338-c1b0374d-0a3d-4fba-93b2-577e94444549.jpeg)
: