SYNERGY-1307 Language reading on linux
symless/synergy-core pull request #7114
Opened 2021-10-29 14:39 UTC by SerhiiGadzhilov

Under this PR I changed reading languages on the Linux system to use Xkb API instead of reading the language file.
Also I included changes for SYNERGY-854 into this PR

2021-11-02 13:58 UTC, nbolton requested changes

2021-11-02 13:58 UTC, nbolton commented on src/lib/client/ServerProxy.cpp
> +              "You need to install these languages on this computer and restart synergy app to enable support for multiple languages: "
Let's change to "and restart Synergy"

2021-11-02 15:51 UTC, SerhiiGadzhilov commented on src/lib/client/ServerProxy.cpp
> +              "You need to install these languages on this computer and restart synergy app to enable support for multiple languages: "
Fixed

2021-11-03 09:47 UTC, nbolton approved these changes

2021-11-03 09:50 UTC, merged