New design for the about screen
symless/synergy-core pull request #7197
Opened 2022-06-29 14:45 UTC by SerhiiGadzhilov

2022-06-29 16:09 UTC, SerhiiGadzhilov commented on ChangeLog
> +- #7197 New design for the about screen
Fixed

2022-06-29 16:10 UTC, SerhiiGadzhilov commented on src/gui/src/CreditsLoader.cpp
> +    const auto ELIT_BACKERS_URL = "https://api.symless.com/credits/elite-backers";
Fixed.
Thank you!

2022-06-30 07:40 UTC, nbolton submitted a review, later dismissed

2022-06-30 10:06 UTC, nbolton requested changes

2022-06-30 10:06 UTC, nbolton commented on src/gui/src/AboutDialogBase.ui
> +      <string notr="true">&lt;a href=&quot;https://symless.com/synergy/credits&quot; style=&quot;color: #4285F4;&quot;&gt;View the complete credits&lt;/a&gt;</string>
@SerhiiGadzhilov

2022-06-30 10:06 UTC, nbolton commented on src/gui/src/AboutDialogBase.ui
> +      <string>&lt;a href=&quot;https://symless.com/synergy/account-status&quot; style=&quot;color: #4285F4;&quot;&gt;Become an Elite Backer&lt;/a&gt;</string>
@SerhiiGadzhilov

2022-06-30 10:20 UTC, nbolton approved these changes

2022-06-30 11:48 UTC, SerhiiGadzhilov commented on src/gui/src/AboutDialogBase.ui
> +      <string>&lt;a href=&quot;https://symless.com/synergy/account-status&quot; style=&quot;color: #4285F4;&quot;&gt;Become an Elite Backer&lt;/a&gt;</string>
Fixed

2022-06-30 11:48 UTC, merged